services:
  tvinstasera_bot:
    build: .
    container_name: tvinstasera_bot
    volumes:
      - ./data:/usr/src/app/data
    environment:
      - TZ=Europe/Rome
    env_file:
      - ./.env
    restart: unless-stopped