services:
  tvinstasera_bot:
    build: .
    container_name: tvinstasera_bot
    volumes:
      - ./data:/usr/src/app/data
    environment:
      - API_ID=<your-api-id>
      - API_HASH=<your-api-hash>
      - BOT_TOKEN=<your-bot-token>
      - TZ=Europe/Rome
    restart: unless-stopped